// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/testComp/A.vue')['default']
    B: typeof import('./src/components/testComp/B.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    Preview: typeof import('./src/components/Preview.vue')['default']
    Render: typeof import('./src/components/Render.vue')['default']
  }
}
